"""Continuous semigroup generated by the canonical E47 kernel.

The E47 heat semigroup is

    S(t) = exp(-t K^2),    t >= 0,

where

    K = (C - 6 I)(C - 30 I).

For the canonical carrier V_2^{tensor 3}, K is Hermitian and

    spec(K^2) = {0, 11664, 12544, 19600, 32400, 186624}.

Consequently S(t) is a Hermitian positive contraction, fixes ker(K), obeys

    S(t + s) = S(t) S(s),

and converges in operator norm to the orthogonal projector P47 onto ker(K):

    ||S(t) - P47||_2 = exp(-11664 t).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

import numpy as np
from numpy.typing import ArrayLike, NDArray


ComplexArray = NDArray[np.complex128]

CARRIER_DIMENSION: Final[int] = 125
E47_DIMENSION: Final[int] = 47
CANONICAL_SPECTRAL_GAP: Final[int] = 11_664
CANONICAL_K2_NORM: Final[int] = 186_624
DEFAULT_TIME: Final[float] = 1.0e-3
DEFAULT_SECOND_TIME: Final[float] = 7.5e-4


@dataclass(frozen=True)
class SemigroupValidation:
    """Structured certificate for S(t) = exp(-t K^2)."""

    valid: bool
    time: float
    second_time: float
    carrier_dimension: int
    kernel_dimension: int
    complement_dimension: int
    spectral_gap: float
    k2_max_eigenvalue: float
    semigroup_min_eigenvalue: float
    semigroup_max_eigenvalue: float
    expected_decay_bound: float
    identity_residual: float
    hermitian_residual: float
    positivity_violation: float
    contraction_violation: float
    kernel_fixed_residual: float
    projector_commutator_residual: float
    semigroup_law_residual: float
    asymptotic_projector_residual: float
    tolerance: float
    errors: tuple[str, ...]


def _as_square_matrix(matrix: ArrayLike, *, name: str) -> ComplexArray:
    """Convert an input to a finite square complex matrix."""

    array = np.asarray(matrix, dtype=np.complex128)

    if array.ndim != 2:
        raise ValueError(f"{name} must be two-dimensional; got ndim={array.ndim}.")

    rows, columns = array.shape
    if rows != columns:
        raise ValueError(f"{name} must be square; got shape {array.shape}.")

    if rows == 0:
        raise ValueError(f"{name} must be non-empty.")

    if not np.all(np.isfinite(array)):
        raise ValueError(f"{name} contains non-finite entries.")

    return array


def _validate_time(value: float, *, name: str) -> float:
    """Return a finite non-negative semigroup time."""

    result = float(value)
    if not np.isfinite(result):
        raise ValueError(f"{name} must be finite.")
    if result < 0.0:
        raise ValueError(f"{name} must be non-negative; got {result!r}.")
    return result


def _kernel_square_eigendecomposition(
    kernel: ArrayLike,
) -> tuple[ComplexArray, NDArray[np.float64]]:
    """Diagonalize the Hermitian part of K^2."""

    K = _as_square_matrix(kernel, name="kernel")
    K2 = K @ K
    K2_hermitian = 0.5 * (K2 + K2.conj().T)
    eigenvalues, eigenvectors = np.linalg.eigh(K2_hermitian)
    return eigenvectors, eigenvalues


def construct_semigroup(
    kernel: ArrayLike,
    time: float,
) -> ComplexArray:
    """Construct S(t) = exp(-t K^2) by Hermitian spectral calculus."""

    t = _validate_time(time, name="time")
    eigenvectors, eigenvalues = _kernel_square_eigendecomposition(kernel)
    factors = np.exp(-t * eigenvalues)
    return (eigenvectors * factors) @ eigenvectors.conj().T


def apply_semigroup(
    semigroup: ArrayLike,
    state: ArrayLike,
) -> ComplexArray:
    """Apply a semigroup matrix to one state or columns of states."""

    S = _as_square_matrix(semigroup, name="semigroup")
    state_array = np.asarray(state, dtype=np.complex128)

    if state_array.ndim not in (1, 2):
        raise ValueError(
            "state must be a vector or a matrix whose columns are states."
        )

    if state_array.shape[0] != S.shape[0]:
        raise ValueError(
            "state dimension does not match semigroup: "
            f"{state_array.shape[0]} != {S.shape[0]}."
        )

    if not np.all(np.isfinite(state_array)):
        raise ValueError("state contains non-finite entries.")

    return S @ state_array


def decay_bound(time: float, spectral_gap: float = CANONICAL_SPECTRAL_GAP) -> float:
    """Return exp(-time * spectral_gap), the complement norm bound."""

    t = _validate_time(time, name="time")
    gap = float(spectral_gap)

    if not np.isfinite(gap) or gap < 0.0:
        raise ValueError("spectral_gap must be finite and non-negative.")

    return float(np.exp(-t * gap))


def time_for_tolerance(
    tolerance: float,
    spectral_gap: float = CANONICAL_SPECTRAL_GAP,
) -> float:
    """Return the least theorem-level time with exp(-gap*t) <= tolerance."""

    tol = float(tolerance)
    gap = float(spectral_gap)

    if not np.isfinite(tol) or not 0.0 < tol < 1.0:
        raise ValueError("tolerance must lie strictly between 0 and 1.")

    if not np.isfinite(gap) or gap <= 0.0:
        raise ValueError("spectral_gap must be finite and strictly positive.")

    return float(-np.log(tol) / gap)


def validate_semigroup(
    kernel: ArrayLike,
    projector: ArrayLike | None = None,
    *,
    time: float = DEFAULT_TIME,
    second_time: float = DEFAULT_SECOND_TIME,
    tolerance: float = 1e-10,
    zero_tolerance: float = 1e-8,
) -> SemigroupValidation:
    """Validate the continuous E47 semigroup and its asymptotic projector."""

    t = _validate_time(time, name="time")
    s = _validate_time(second_time, name="second_time")

    if not np.isfinite(tolerance) or tolerance <= 0.0:
        raise ValueError("tolerance must be finite and positive.")

    if not np.isfinite(zero_tolerance) or zero_tolerance <= 0.0:
        raise ValueError("zero_tolerance must be finite and positive.")

    errors: list[str] = []
    K = _as_square_matrix(kernel, name="kernel")
    dimension = K.shape[0]
    identity = np.eye(dimension, dtype=np.complex128)

    kernel_hermitian_residual = float(np.linalg.norm(K - K.conj().T, ord=2))
    if kernel_hermitian_residual > tolerance:
        errors.append(
            "Kernel is not Hermitian within tolerance: "
            f"{kernel_hermitian_residual:.3e} > {tolerance:.3e}."
        )

    eigenvectors, k2_eigenvalues = _kernel_square_eigendecomposition(K)
    k2_min = float(k2_eigenvalues[0])
    k2_max = float(k2_eigenvalues[-1])

    if k2_min < -zero_tolerance:
        errors.append(
            f"K^2 is not positive semidefinite: min eigenvalue={k2_min:.3e}."
        )

    zero_mask = np.abs(k2_eigenvalues) <= zero_tolerance
    kernel_dimension = int(np.count_nonzero(zero_mask))
    complement_dimension = dimension - kernel_dimension
    positive_eigenvalues = k2_eigenvalues[~zero_mask]
    spectral_gap = (
        float(positive_eigenvalues[0]) if positive_eigenvalues.size else 0.0
    )

    def from_time(value: float) -> ComplexArray:
        factors = np.exp(-value * k2_eigenvalues)
        return (eigenvectors * factors) @ eigenvectors.conj().T

    S0 = from_time(0.0)
    St = from_time(t)
    Ss = from_time(s)
    Sts = from_time(t + s)

    identity_residual = float(np.linalg.norm(S0 - identity, ord=2))
    hermitian_residual = float(np.linalg.norm(St - St.conj().T, ord=2))
    semigroup_law_residual = float(np.linalg.norm(Sts - St @ Ss, ord=2))

    semigroup_eigenvalues = np.linalg.eigvalsh(0.5 * (St + St.conj().T))
    min_semigroup_eigenvalue = float(semigroup_eigenvalues[0])
    max_semigroup_eigenvalue = float(semigroup_eigenvalues[-1])
    positivity_violation = max(0.0, -min_semigroup_eigenvalue)
    contraction_violation = max(0.0, max_semigroup_eigenvalue - 1.0)

    if identity_residual > tolerance:
        errors.append(f"S(0) != I within tolerance: {identity_residual:.3e}.")

    if hermitian_residual > tolerance:
        errors.append(f"S(t) is not Hermitian: residual={hermitian_residual:.3e}.")

    if positivity_violation > tolerance:
        errors.append(
            "S(t) is not positive semidefinite within tolerance: "
            f"violation={positivity_violation:.3e}."
        )

    if contraction_violation > tolerance:
        errors.append(
            "S(t) is not a contraction within tolerance: "
            f"violation={contraction_violation:.3e}."
        )

    if semigroup_law_residual > tolerance:
        errors.append(
            "Semigroup law failed: "
            f"||S(t+s)-S(t)S(s)||={semigroup_law_residual:.3e}."
        )

    kernel_fixed_residual = float("nan")
    projector_commutator_residual = float("nan")
    asymptotic_projector_residual = float("nan")
    expected_decay_bound = decay_bound(t, spectral_gap) if spectral_gap > 0.0 else 0.0

    if projector is not None:
        P = _as_square_matrix(projector, name="projector")
        if P.shape != K.shape:
            raise ValueError(
                "projector and kernel must have the same shape; "
                f"got {P.shape} and {K.shape}."
            )

        projector_hermitian_residual = float(
            np.linalg.norm(P - P.conj().T, ord=2)
        )
        projector_idempotence_residual = float(
            np.linalg.norm(P @ P - P, ord=2)
        )

        if projector_hermitian_residual > tolerance:
            errors.append(
                "Projector is not Hermitian within tolerance: "
                f"{projector_hermitian_residual:.3e}."
            )

        if projector_idempotence_residual > tolerance:
            errors.append(
                "Projector is not idempotent within tolerance: "
                f"{projector_idempotence_residual:.3e}."
            )

        projector_rank = int(
            np.count_nonzero(
                np.linalg.eigvalsh(0.5 * (P + P.conj().T)) > 0.5
            )
        )
        if projector_rank != kernel_dimension:
            errors.append(
                "Projector rank does not equal dim ker(K): "
                f"{projector_rank} != {kernel_dimension}."
            )

        kernel_fixed_residual = float(np.linalg.norm(St @ P - P, ord=2))
        projector_commutator_residual = float(
            np.linalg.norm(St @ P - P @ St, ord=2)
        )
        asymptotic_projector_residual = float(np.linalg.norm(St - P, ord=2))

        if kernel_fixed_residual > tolerance:
            errors.append(
                "S(t) does not fix the supplied kernel projector: "
                f"{kernel_fixed_residual:.3e}."
            )

        if projector_commutator_residual > tolerance:
            errors.append(
                "S(t) does not commute with the supplied projector: "
                f"{projector_commutator_residual:.3e}."
            )

        convergence_limit = expected_decay_bound + 20.0 * np.finfo(float).eps
        if asymptotic_projector_residual > convergence_limit + tolerance:
            errors.append(
                "S(t) does not satisfy the spectral decay bound: "
                f"{asymptotic_projector_residual:.3e} > "
                f"{convergence_limit:.3e}."
            )

    if dimension == CARRIER_DIMENSION:
        if kernel_dimension != E47_DIMENSION:
            errors.append(
                "Canonical carrier has incorrect kernel dimension: "
                f"{kernel_dimension} != {E47_DIMENSION}."
            )

        if not np.isclose(
            spectral_gap,
            CANONICAL_SPECTRAL_GAP,
            rtol=0.0,
            atol=zero_tolerance,
        ):
            errors.append(
                "Canonical K^2 spectral gap is incorrect: "
                f"{spectral_gap:.12g} != {CANONICAL_SPECTRAL_GAP}."
            )

        if not np.isclose(
            k2_max,
            CANONICAL_K2_NORM,
            rtol=0.0,
            atol=zero_tolerance,
        ):
            errors.append(
                "Canonical maximum K^2 eigenvalue is incorrect: "
                f"{k2_max:.12g} != {CANONICAL_K2_NORM}."
            )

    return SemigroupValidation(
        valid=not errors,
        time=t,
        second_time=s,
        carrier_dimension=dimension,
        kernel_dimension=kernel_dimension,
        complement_dimension=complement_dimension,
        spectral_gap=spectral_gap,
        k2_max_eigenvalue=k2_max,
        semigroup_min_eigenvalue=min_semigroup_eigenvalue,
        semigroup_max_eigenvalue=max_semigroup_eigenvalue,
        expected_decay_bound=expected_decay_bound,
        identity_residual=identity_residual,
        hermitian_residual=hermitian_residual,
        positivity_violation=positivity_violation,
        contraction_violation=contraction_violation,
        kernel_fixed_residual=kernel_fixed_residual,
        projector_commutator_residual=projector_commutator_residual,
        semigroup_law_residual=semigroup_law_residual,
        asymptotic_projector_residual=asymptotic_projector_residual,
        tolerance=float(tolerance),
        errors=tuple(errors),
    )


def require_valid_semigroup(
    kernel: ArrayLike,
    projector: ArrayLike | None = None,
    *,
    time: float = DEFAULT_TIME,
    second_time: float = DEFAULT_SECOND_TIME,
    tolerance: float = 1e-10,
    zero_tolerance: float = 1e-8,
) -> SemigroupValidation:
    """Validate the semigroup and raise one aggregated error on failure."""

    validation = validate_semigroup(
        kernel,
        projector,
        time=time,
        second_time=second_time,
        tolerance=tolerance,
        zero_tolerance=zero_tolerance,
    )

    if not validation.valid:
        details = "\n".join(
            f"  {index}. {message}"
            for index, message in enumerate(validation.errors, start=1)
        )
        raise ValueError(f"E47 semigroup validation failed:\n{details}")

    return validation


__all__ = [
    "CANONICAL_K2_NORM",
    "CANONICAL_SPECTRAL_GAP",
    "CARRIER_DIMENSION",
    "DEFAULT_SECOND_TIME",
    "DEFAULT_TIME",
    "E47_DIMENSION",
    "SemigroupValidation",
    "apply_semigroup",
    "construct_semigroup",
    "decay_bound",
    "require_valid_semigroup",
    "time_for_tolerance",
    "validate_semigroup",
]


if __name__ == "__main__":
    from e47.projector import construct_e47_projector
    from e47.su2_kernel import (
        build_e47_operators,
        require_valid_e47_kernel,
        validate_e47_kernel,
    )

    operators = build_e47_operators()
    kernel_validation = validate_e47_kernel(operators)
    require_valid_e47_kernel(kernel_validation)

    projector_data = construct_e47_projector(operators)

    certificate = require_valid_semigroup(
        operators.kernel,
        projector_data.projector,
    )

    print(certificate)
